const types = {
    MAKE_REQUEST_START: "MAKE_REQUEST_START",
  
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
   
    CREATE_ARTIFACT_SUCCESS: "CREATE_ARTIFACT_SUCCESS",
  
    LOGOUT: "LOGOUT",
  };
  
  export default types;
  